AWSTemplateFormatVersion: '2010-09-09'
Description: 'Cognito User Pool and Client for MFE Demo Application'

Parameters:
  ApplicationName:
    Type: String
    Description: 'Application name (used for naming resources)'
    Default: 'mfe-demo'

  Environment:
    Type: String
    Description: 'Environment name'
    Default: 'production'
    AllowedValues:
      - development
      - staging
      - production

  DomainName:
    Type: String
    Description: 'Domain name for the application (for callback URLs)'
    AllowedPattern: '^[a-z0-9][a-z0-9-.]+(\.com|\.net|\.org|\.io|\.co|\.dev)$'

Resources:
  # Cognito User Pool
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub '${ApplicationName}-${Environment}-user-pool'
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          TemporaryPasswordValidityDays: 7
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: false
        - Name: name
          AttributeDataType: String
          Required: false
          Mutable: true
        - Name: family_name
          AttributeDataType: String
          Required: false
          Mutable: true
        - Name: given_name
          AttributeDataType: String
          Required: false
          Mutable: true
      UserAttributeUpdateSettings:
        AttributesRequireVerificationBeforeUpdate:
          - email
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      UserPoolAddOns:
        AdvancedSecurityMode: AUDIT
      MfaConfiguration: OPTIONAL
      EnabledMfas:
        - SOFTWARE_TOKEN_MFA
      UserPoolTags:
        Name: !Sub '${ApplicationName}-${Environment}-user-pool'
        Environment: !Ref Environment

  # Cognito User Pool Client
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub '${ApplicationName}-${Environment}-web-client'
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      RefreshTokenValidity: 30
      AccessTokenValidity: 60
      IdTokenValidity: 60
      TokenValidityUnits:
        RefreshToken: days
        AccessToken: minutes
        IdToken: minutes
      ReadAttributes:
        - email
        - name
        - family_name
        - given_name
        - email_verified
      WriteAttributes:
        - email
        - name
        - family_name
        - given_name
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_PASSWORD_AUTH
      PreventUserExistenceErrors: ENABLED
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      AllowedOAuthFlowsUserPoolClient: true
      CallbackURLs:
        - !Sub 'https://${DomainName}'
        - !Sub 'https://${DomainName}/'
        - !Sub 'https://${DomainName}/login'
        - 'http://localhost:3000'
        - 'http://localhost:3000/'
        - 'http://localhost:3000/login'
      LogoutURLs:
        - !Sub 'https://${DomainName}'
        - !Sub 'https://${DomainName}/'
        - 'http://localhost:3000'
        - 'http://localhost:3000/'
      SupportedIdentityProviders:
        - COGNITO

  # Cognito User Pool Domain (for hosted UI)
  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub '${ApplicationName}-${Environment}-${AWS::AccountId}'
      UserPoolId: !Ref UserPool

  # Admin User Group
  AdminGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: admin
      Description: 'Administrator group with full access'
      UserPoolId: !Ref UserPool
      Precedence: 0

  # User Group
  UserGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: user
      Description: 'Standard user group'
      UserPoolId: !Ref UserPool
      Precedence: 1

Outputs:
  UserPoolId:
    Description: 'Cognito User Pool ID'
    Value: !Ref UserPool
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolId'

  UserPoolArn:
    Description: 'Cognito User Pool ARN'
    Value: !GetAtt UserPool.Arn
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolArn'

  UserPoolClientId:
    Description: 'Cognito User Pool Client ID'
    Value: !Ref UserPoolClient
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolClientId'

  UserPoolDomain:
    Description: 'Cognito User Pool Domain'
    Value: !Ref UserPoolDomain
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolDomain'

  HostedUIURL:
    Description: 'Cognito Hosted UI URL'
    Value: !Sub 'https://${UserPoolDomain}.auth.${AWS::Region}.amazoncognito.com'
    Export:
      Name: !Sub '${AWS::StackName}-HostedUIURL'

  AdminGroupName:
    Description: 'Admin Group Name'
    Value: !Ref AdminGroup
    Export:
      Name: !Sub '${AWS::StackName}-AdminGroupName'

  UserGroupName:
    Description: 'User Group Name'
    Value: !Ref UserGroup
    Export:
      Name: !Sub '${AWS::StackName}-UserGroupName'
